### ISSUE TITLE
Next Rain Forecast as None

### ISSUE THREAD

**Issue by metbril** [gieljnssns/buienalarm-sensor-homeassistant#11]
Currently next rail forecast is shown as "-1 minutes". This doesn't look good in the UI. Why not set the sensor value to `None` if it is computed as `-1`?

If you like I can submit a PR.

**Comment by metbril** [comment]
Other values could be "Unavailable" or "Unknow" but just `None` seems most appropriate here.

**Comment by gieljnssns** [comment]
A PR is alway welcome…

**Comment by metbril** [comment]
Hope you appreciate my contributions.
