### ISSUE TITLE
Setup of sensor platform buienalarm is taking over 10 seconds.

### ISSUE THREAD

**Issue by TheFes** [gieljnssns/buienalarm-sensor-homeassistant#20]
**Describe the bug**
The sensor is no longer working, it is no longer to be found in HA

**Any errors**
```
Setup of sensor platform buienalarm is taking over 10 seconds.
```

**Config yaml**
In a seperate buienalarm.yaml which is included by sensor.yaml
```
platform: buienalarm
timeframe: 15
name: buienalarm
monitored_conditions:
  - temperature
  - precipitation
  - precipitation_forecast_average
  - precipitation_forecast_total
  - next_rain_forecast
```

**Screenshots**
![image](https://user-images.githubusercontent.com/28803438/120173219-1b620b00-c204-11eb-9550-35f08fe4bf2f.png)

**Comment by JohnnyM84** [comment]
I think it's a problem with the api of buienalarm, yesterday i had the same this plugin and the neerslag app had no data of buienalarm. today it's working again.

**Comment by StevenLooman** [comment]
I think this issue can be closed @gieljnssns

**Comment by gieljnssns** [comment]
Thanks @StevenLooman
