### ISSUE TITLE
After updating to v1.8 it is still not working

### ISSUE THREAD

**Issue by bartjanisse** [gieljnssns/buienalarm-sensor-homeassistant#23]
**Describe the bug**
I had no luck with v1.7 so I was happy to see there was a v1.8. I updated but it still seems not to work. See the errors below for the log information. 

I really hope you get it to work properly. Anyway thanks a lot for your effort

**Any errors**
```

Logger: custom_components.buienalarm
Source: helpers/update_coordinator.py:200 
Integration: buienalarm (documentation) 
First occurred: 18:38:05 (9 occurrences) 
Last logged: 21:18:05

Error requesting buienalarm data: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?

```

**Config yaml**
```
Installed with HACS
```
**Screenshot**

![image](https://user-images.githubusercontent.com/11034947/126385254-d5142581-68e2-4e20-acad-a8bf1c18bb00.jpeg)

**Comment by mrpharderwijk** [comment]
Since yesterday I'm experiencing the above as well :-(...

**Comment by StevenLooman** [comment]
Since 1.9 this issue should be solved. I think this issue can be closed @gieljnssns
