### ISSUE TITLE
Version 1.9 gateway errors

### ISSUE THREAD

**Issue by StevenBoelhouwer** [gieljnssns/buienalarm-sensor-homeassistant#26]
**Describe the bug**
Since a couple of days a gateway error is shown

Error in log:
'Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)'

**Comment by gieljnssns** [comment]
Duplicate of https://github.com/gieljnssns/buienalarm-sensor-homeassistant/issues/27
