### ISSUE TITLE
Next rain forcast blijft hangen op 5min

### ISSUE THREAD

**Issue by johanneswilkens** [gieljnssns/buienalarm-sensor-homeassistant#4]
De nieuw toegevoegde sensor die het aantal minuten tot neerslag aan zou moeten geven blijft hangen op 5 minuten, en springt wanneer het weer droog is op -1 of een nieuwe tijd, wat ook te zien is in de screenshot. 
Deze sensor is superchill voor automations, dus zou leuk zijn als ie het nog beter doet.
![E2C2A48E-F01B-4CAD-B6C3-4AE51A69CD2F](https://user-images.githubusercontent.com/54482490/81738596-3b5c4a80-949a-11ea-831e-fa092114ac6f.png)

**Comment by gieljnssns** [comment]
Ik heb een update naar Hacs gestuurd. Nu zou de sensor effectief 0minuten moeten aangeven wanneer het regent.
Maar verder aftellen van 5min naar beneden is niet mogelijk, buienalarm geeft maar om de 5minuten nieuwe data door, dus het aftellen zal altijd in blokken van 5 gebeuren.

**Comment by nelbs** [comment]
Misschien een idee om het tijdstip waarop het begint met regenen weer te geven in plaats van de tijd tot het moment. Hierdoor is de info altijd actueel en ben je minder afhankelijk van de refreshtijd van de sensor. Als je wil kan je dan zelf een template sensor maken die iedere minuut aftelt.

**Comment by johanneswilkens** [comment]
Ik zal hem updaten vanavond, nu nog even wachten op regen 😂
@nelbs Andersom zou ook kunnen, als de data sowieso al intervallen van 5 min heeft kun je de tijd berekenen met een template

**Comment by nelbs** [comment]
Klopt, zolang de sensor netjes iedere minuut de data ophaald gaat het goed. Echter als er om wat voor reden dan ook iets niet goed gaat met refreshen dan klopt de data niet meer.

**Comment by gieljnssns** [comment]
Ik veronderstel dat het nu in orde is?

**Comment by johanneswilkens** [comment]
Helaas heb ik het nog niet kunnen testen met regen maar ga er wel vanuit dat het werkt
